### ISSUE TITLE
Slackからの受取部を作成

### ISSUE THREAD

**Issue by akakou** [kazu16182718/classtream#3]
# Slackからの受取部を作成
Slackのボットから、各情報を取得する。
トークン情報はJSON形式で、/src/config.jsonから読み出すこととする。
また実装は、[旧classtream](https://github.com/2j-developer/clastream)を参考にすること。
## 参考になりそうなファイル
> /index.js
> => clastream_slackbot()

# 備考
## ブランチ
> feature/slack

## ディレクトリ
> /src/index.html
> /src/config.json

## config.jsonの形式
```json
{
    "token": "slackのトークン"
}
```

**Comment by akakou** [comment]
https://github.com/kazu16182718/classtream/blob/feature/slack/src/index.html

の余計なコメントアウトと、突然のJSDoc的なコメントは消しません？

あとコメントは、日本語に統一してくれると嬉しいです。

**Comment by akakou** [comment]
今更で申し訳ありませんが、[このコーディング規約](https://github.com/kazu16182718/classtream/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%81%99%E3%82%8B%E4%B8%8A%E3%81%A7%E3%81%AE%E3%80%81%E5%83%95%E3%81%A8%E3%81%AE%E7%B4%84%E6%9D%9F%E3%81%A0%E3%82%88%EF%BC%81)に沿うように修正お願いできませんか？

**Comment by kazu16182718** [comment]
了解です,明日中に修正します.
