### ISSUE TITLE
グラフの表示

### ISSUE THREAD

**Issue by akakou** [kazu16182718/classtream#4]
# グラフの表示
chart.jsを用いて、[line-boundaries](http://www.chartjs.org/samples/latest/charts/area/line-boundaries.html)をもとに、グラフを表示させること。

# グラフの詳細
* 二本の線を用いたグラフを表示させること。
    * 赤色
        * :+1: の数を表す。
    * 青色
         * :-1: の数を表す。
* x軸とグラフの値の間となる面を、背景色以外で塗らないこと。
* x軸の値は常に0とし、それ以下は存在しないこととする。

# 備考
## ブランチ
> feature/chart

## ディレクトリ
> /src/index.html
> /src/script/graph.js

## その他
chart.jsは、npmを使ってインストールすること。

**Comment by unyooon** [comment]
完成
